#%D_ARROW% to get arrow
#%NEWLINE% to write in other line
#& + number to write with color
# %TIME% to get countdown
# yyyy-MM-dd hh:mm:ss to get time

motd:
  time-zone: "EST"

profile:
  test:
    message: "&3Welcome &3to the server"
    count-down: true # true or false
    time-to-expire: "2025-12-31 07:50:00"
    text-when-expire: "Time finish"


